---
version: '3'
services:
    build-webapp:
      build: 
        context: /home/ubuntu/repo
        dockerfile: Dockerfile 
      volumes: 
        - data:/usr/local/tomcat/webapps
        - wdata:/opt/tomcat/webapps

    webserver:
        image: woahbase/alpine-tomcat:x86_64
        ports: 
          - 8080:8080        
        depends_on:
          - build-webapp
        volumes: 
        - wdata:/opt/tomcat/webapps
      

volumes: 
  data:
  wdata:

...
