---
version: '3'
services:
    build-webapp:
      build: 
        context: /home/ubuntu/repo
        dockerfile: Dockerfile 
      volumes: 
        - data:/usr/local/tomcat/webapps

    webserver:
        image: tomcat:9.0.84-jdk11
        ports: 
          - 8080:8080        
        depends_on:
          - build-webapp
        volumes: 
        - data:/usr/local/tomcat/webapps
      

volumes: 
  data:

...
